export const env = {
  PUBLIC_SITE_URL: import.meta.env.PUBLIC_SITE_URL,
  PUBLIC_WHATSAPP_NUMBER: import.meta.env.PUBLIC_WHATSAPP_NUMBER,
  PUBLIC_INSTAGRAM_URL: import.meta.env.PUBLIC_INSTAGRAM_URL,
  PUBLIC_FACEBOOK_URL: import.meta.env.PUBLIC_FACEBOOK_URL,
};
