name: Deploy

on:
  push:
    tags:
      - "v"
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Hostinger
      url: https://psi.leticiabritto.com
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{secrets.COOLIFY_WEBHOOK}}' --header 'Authorization: Bearer ${{secrets.COOLIFY_TOKEN}}'