name: Deploy

on:
  push:
    tags:
      - "v*"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to Hostinger
        uses: hostinger/deploy-on-vps@v1
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ secrets.HOSTINGER_VM_ID }}
          project-name: psi-leticia-brito
          personal-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          docker-compose-path: ./docker-compose.yml
          environment-variables: |
            NODE_ENV=production